name: Task 2 - Secure CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: write
  packages: write
  security-events: write
  id-token: write


env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/ledger-api
  IMAGE_TAG: ${{ github.sha }}


jobs:

############################################################
# BUILD + SECURITY SCAN
############################################################

  security-ci:

    name: Build Scan and Security Gates

    runs-on: ubuntu-latest


    steps:

    ########################################################
    # Checkout
    ########################################################

    - name: Checkout Repository
      uses: actions/checkout@v4


    ########################################################
    # Docker Setup
    ########################################################

    - name: Docker Buildx Setup
      uses: docker/setup-buildx-action@v3



    ########################################################
    # Build Image
    ########################################################

    - name: Build Docker Image
      run: |

        docker build \
          -f ledger-api-assignment/app/Dockerfile \
          -t ledger-api:test \
          ledger-api-assignment/app



    - name: Verify Image

      run: |

        docker images



############################################################
# SAST
############################################################


    - name: Run Semgrep SAST

      uses: semgrep/semgrep-action@v1

      with:

        config: p/security-audit

      continue-on-error: true





############################################################
# TRIVY INSTALL
############################################################


    - name: Install Trivy

      run: |

        sudo apt-get update

        sudo apt-get install -y curl

        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
        | sudo sh -s -- -b /usr/local/bin

        trivy --version




############################################################
# IMAGE SCAN
############################################################


    - name: Trivy Image Scan

      run: |


        trivy image \
        --severity HIGH,CRITICAL \
        --ignore-unfixed \
        --exit-code 0 \
        ledger-api:test




############################################################
# FILE SYSTEM SCAN
############################################################


    - name: Trivy Filesystem Scan


      run: |


        trivy fs \
        --severity HIGH,CRITICAL \
        --ignore-unfixed \
        --exit-code 0 \
        .




############################################################
# SECRET SCAN
############################################################


    - name: Gitleaks Scan


      uses: gitleaks/gitleaks-action@v2


      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      continue-on-error: true




############################################################
# LOGIN GHCR
############################################################



    - name: Login to GHCR


      uses: docker/login-action@v3


      with:

        registry: ghcr.io

        username: ${{ github.actor }}

        password: ${{ secrets.GITHUB_TOKEN }}





############################################################
# PUSH IMAGE
############################################################


    - name: Tag Image


      run: |


        docker tag ledger-api:test \
        $IMAGE_NAME:$IMAGE_TAG




    - name: Push Image


      run: |


        docker push \
        $IMAGE_NAME:$IMAGE_TAG





############################################################
# COSIGN INSTALL
############################################################


    - name: Install Cosign


      uses: sigstore/cosign-installer@v3




############################################################
# COSIGN SIGN
############################################################


    - name: Sign Container Image


      run: |


        cosign sign \
        --yes \
        $IMAGE_NAME:$IMAGE_TAG




############################################################
# VERIFY SIGNATURE
############################################################


    - name: Verify Signature


      run: |


        cosign verify \
        $IMAGE_NAME:$IMAGE_TAG \
        --certificate-identity-regexp \
        "https://github.com/${{ github.repository }}/.*" \
        --certificate-oidc-issuer \
        "https://token.actions.githubusercontent.com"





############################################################
# SLSA PROVENANCE
############################################################


    - name: Generate SLSA Provenance


      uses: actions/attest-build-provenance@v1


      with:

        subject-name: ${{ env.IMAGE_NAME }}

        subject-digest: ${{ steps.build.outputs.digest }}

        push-to-registry: true





############################################################
# REPORTS
############################################################


    - name: Create Reports


      run: |


        mkdir reports

        docker images > reports/docker-images.txt




    - name: Upload Security Reports


      if: always()


      uses: actions/upload-artifact@v4


      with:


        name: task2-security-reports


        path: reports/